/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedRecurringRouteImport } from './routes/_authenticated/recurring'
import { Route as AuthenticatedReceiptsRouteImport } from './routes/_authenticated/receipts'
import { Route as AuthenticatedHouseholdRouteImport } from './routes/_authenticated/household'
import { Route as AuthenticatedFinancesRouteImport } from './routes/_authenticated/finances'
import { Route as AuthenticatedAddRouteImport } from './routes/_authenticated/add'
import { Route as AuthenticatedEditIdRouteImport } from './routes/_authenticated/edit.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecurringRoute = AuthenticatedRecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReceiptsRoute = AuthenticatedReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHouseholdRoute = AuthenticatedHouseholdRouteImport.update({
  id: '/household',
  path: '/household',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinancesRoute = AuthenticatedFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAddRoute = AuthenticatedAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEditIdRoute = AuthenticatedEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/add': typeof AuthenticatedAddRoute
  '/finances': typeof AuthenticatedFinancesRoute
  '/household': typeof AuthenticatedHouseholdRoute
  '/receipts': typeof AuthenticatedReceiptsRoute
  '/recurring': typeof AuthenticatedRecurringRoute
  '/edit/$id': typeof AuthenticatedEditIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/add': typeof AuthenticatedAddRoute
  '/finances': typeof AuthenticatedFinancesRoute
  '/household': typeof AuthenticatedHouseholdRoute
  '/receipts': typeof AuthenticatedReceiptsRoute
  '/recurring': typeof AuthenticatedRecurringRoute
  '/': typeof AuthenticatedIndexRoute
  '/edit/$id': typeof AuthenticatedEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/add': typeof AuthenticatedAddRoute
  '/_authenticated/finances': typeof AuthenticatedFinancesRoute
  '/_authenticated/household': typeof AuthenticatedHouseholdRoute
  '/_authenticated/receipts': typeof AuthenticatedReceiptsRoute
  '/_authenticated/recurring': typeof AuthenticatedRecurringRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/edit/$id': typeof AuthenticatedEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/add'
    | '/finances'
    | '/household'
    | '/receipts'
    | '/recurring'
    | '/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/add'
    | '/finances'
    | '/household'
    | '/receipts'
    | '/recurring'
    | '/'
    | '/edit/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/add'
    | '/_authenticated/finances'
    | '/_authenticated/household'
    | '/_authenticated/receipts'
    | '/_authenticated/recurring'
    | '/_authenticated/'
    | '/_authenticated/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recurring': {
      id: '/_authenticated/recurring'
      path: '/recurring'
      fullPath: '/recurring'
      preLoaderRoute: typeof AuthenticatedRecurringRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/receipts': {
      id: '/_authenticated/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof AuthenticatedReceiptsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/household': {
      id: '/_authenticated/household'
      path: '/household'
      fullPath: '/household'
      preLoaderRoute: typeof AuthenticatedHouseholdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finances': {
      id: '/_authenticated/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof AuthenticatedFinancesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/add': {
      id: '/_authenticated/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AuthenticatedAddRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/edit/$id': {
      id: '/_authenticated/edit/$id'
      path: '/edit/$id'
      fullPath: '/edit/$id'
      preLoaderRoute: typeof AuthenticatedEditIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAddRoute: typeof AuthenticatedAddRoute
  AuthenticatedFinancesRoute: typeof AuthenticatedFinancesRoute
  AuthenticatedHouseholdRoute: typeof AuthenticatedHouseholdRoute
  AuthenticatedReceiptsRoute: typeof AuthenticatedReceiptsRoute
  AuthenticatedRecurringRoute: typeof AuthenticatedRecurringRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedEditIdRoute: typeof AuthenticatedEditIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAddRoute: AuthenticatedAddRoute,
  AuthenticatedFinancesRoute: AuthenticatedFinancesRoute,
  AuthenticatedHouseholdRoute: AuthenticatedHouseholdRoute,
  AuthenticatedReceiptsRoute: AuthenticatedReceiptsRoute,
  AuthenticatedRecurringRoute: AuthenticatedRecurringRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedEditIdRoute: AuthenticatedEditIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
